services:
  - type: web
    name: django-ecommerce-app
    env: python
    plan: free

    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput

    startCommand: gunicorn ecommerce.wsgi:application

    envVars:
      - key: PYTHON_VERSION
        value: 3.10

      - key: SECRET_KEY
        generateValue: true

      - key: DJANGO_SETTINGS_MODULE
        value: "ecommerce.settings"

      - key: DEBUG
        value: "False"
